import { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { ArrowRight, Check, ChevronDown, CircleHelp, LockKeyhole, Menu, Sparkles, Shield, Wallet, X, Zap } from 'lucide-react'
import { recordRitual, safeApi } from './api'
import './index.css'

const fallback = { balance: 248, entries: [{ content: 'I am making space for a more intentional kind of progress.', mood: 'hopeful' }] }

function App() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [balance, setBalance] = useState(fallback.balance)
  const [entries, setEntries] = useState(fallback.entries)
  const [joined, setJoined] = useState(false)
  const [busy, setBusy] = useState(false)
  const [notice, setNotice] = useState('')

  useEffect(() => {
    Promise.all([safeApi('/coins/balance', fallback), safeApi('/journal/entries', fallback.entries)])
      .then(([coins, journal]) => { setBalance(coins.balance ?? fallback.balance); setEntries(Array.isArray(journal) ? journal : fallback.entries) })
  }, [])

  async function beginRitual() {
    if (busy) return
    setBusy(true); setNotice('')
    const message = `I am choosing a gentler future with Veil.`
    try { await recordRitual(message); setEntries((current) => [{ content: message, mood: 'hopeful' }, ...current]); setNotice('Your intention is safely recorded.') }
    catch { setEntries((current) => [{ content: message, mood: 'hopeful' }, ...current]); setNotice('Saved locally — connect your space to sync it.') }
    finally { setBusy(false); setJoined(true) }
  }

  return <div className="min-h-screen bg-[var(--canvas)] text-[var(--ink)] selection:bg-[var(--soft)] selection:text-[var(--dark)]">
    <header className="fixed inset-x-0 top-0 z-40 border-b border-[var(--line)] bg-[var(--canvas)]/85 backdrop-blur-xl">
      <div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-10">
        <a href="#top" className="flex items-center gap-2 font-semibold tracking-tight"><span className="grid h-9 w-9 place-items-center rounded-full bg-[var(--dark)] text-[var(--soft)]"><Sparkles size={16} /></span><span>zenheaven<span className="text-[var(--accent)]">/</span>veil</span></a>
        <nav className="hidden items-center gap-8 text-sm text-[var(--muted)] md:flex"><a href="#story" className="transition hover:text-[var(--ink)]">The story</a><a href="#protocol" className="transition hover:text-[var(--ink)]">The protocol</a><a href="#signal" className="transition hover:text-[var(--ink)]">Your signal</a><span className="flex items-center gap-2 rounded-full border border-[var(--line)] px-3 py-1.5 text-xs"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-[var(--accent)]" /> network live</span></nav>
        <button className="rounded-full border border-[var(--line)] p-2 md:hidden" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation">{menuOpen ? <X size={19} /> : <Menu size={19} />}</button>
      </div>
      {menuOpen && <nav className="space-y-1 border-t border-[var(--line)] px-5 py-4 text-sm md:hidden"><a className="block py-2" href="#story" onClick={() => setMenuOpen(false)}>The story</a><a className="block py-2" href="#protocol" onClick={() => setMenuOpen(false)}>The protocol</a><a className="block py-2" href="#signal" onClick={() => setMenuOpen(false)}>Your signal</a></nav>}
    </header>

    <main id="top">
      <section className="relative mx-auto grid max-w-7xl gap-14 px-5 pb-20 pt-36 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:px-10 lg:pb-28 lg:pt-48">
        <div className="absolute left-1/2 top-20 -z-10 h-80 w-80 -translate-x-1/2 rounded-full bg-[var(--soft)] opacity-60 blur-3xl lg:left-3/4 lg:top-36" />
        <div><div className="mb-7 flex items-center gap-3 text-xs font-semibold uppercase tracking-[.22em] text-[var(--accent)]"><span className="h-px w-8 bg-[var(--accent)]" /> Web3 zero-knowledge privacy layer</div><h1 className="max-w-4xl text-5xl font-medium leading-[.98] tracking-[-.055em] sm:text-7xl lg:text-[6.6rem]">Privacy is a form of <em className="font-serif font-normal text-[var(--accent)]">care.</em></h1><p className="mt-8 max-w-xl text-lg leading-8 text-[var(--muted)]">Prove what helps. Reveal nothing extra. Veil lets you carry the proof you need without handing over the story behind it.</p><div className="mt-10 flex flex-wrap items-center gap-4"><button onClick={beginRitual} className="group inline-flex items-center gap-3 rounded-full bg-[var(--dark)] px-6 py-3.5 text-sm font-medium text-white transition hover:-translate-y-0.5 hover:shadow-xl" disabled={busy}>{busy ? 'Opening your space…' : joined ? 'Intention recorded' : 'Begin your ritual'}{joined ? <Check size={17} /> : <ArrowRight className="transition group-hover:translate-x-1" size={17} />}</button><a className="group inline-flex items-center gap-2 text-sm font-medium" href="#story">Read the story <ChevronDown className="transition group-hover:translate-y-1" size={16} /></a></div><div className="mt-10 flex items-center gap-4 text-xs text-[var(--muted)]"><span className="flex -space-x-2"><i className="grid h-8 w-8 place-items-center rounded-full border-2 border-[var(--canvas)] bg-[var(--soft)] font-semibold text-[var(--dark)]">A</i><i className="grid h-8 w-8 place-items-center rounded-full border-2 border-[var(--canvas)] bg-[var(--accent)] text-white">M</i><i className="grid h-8 w-8 place-items-center rounded-full border-2 border-[var(--canvas)] bg-[var(--dark)] text-white">+</i></span><span><strong className="text-[var(--ink)]">12,400+</strong> people choosing intentional tech</span></div></div>
        <div className="relative min-h-[420px] overflow-hidden rounded-[2rem] bg-[var(--dark)] p-6 text-white shadow-2xl lg:min-h-[560px] lg:p-8">
          <div className="absolute -right-20 -top-20 h-72 w-72 rounded-full border border-white/10 bg-[var(--accent)]/20 blur-2xl" /><div className="absolute bottom-[-20%] left-[-10%] h-80 w-80 rounded-full border border-[var(--accent)]/30" /><div className="absolute bottom-[-12%] left-[15%] h-64 w-64 rounded-full border border-white/10" />
          <div className="relative flex h-full min-h-[365px] flex-col justify-between lg:min-h-[500px]"><div className="flex items-start justify-between"><span className="rounded-full border border-white/15 px-3 py-1.5 text-[10px] uppercase tracking-[.2em] text-white/60">zenheaven / 00</span><Shield size={20} className="text-[var(--accent)]" /></div><div className="relative mx-auto w-full max-w-sm"><div className="absolute -inset-6 rounded-full border border-white/10" /><div className="absolute -inset-12 rounded-full border border-white/5" /><div className="relative rounded-[1.5rem] border border-white/15 bg-white/10 p-6 backdrop-blur"><div className="flex items-center justify-between text-xs text-white/50"><span>YOUR CURRENT SIGNAL</span><span className="text-[var(--accent)]">● synced</span></div><div className="mt-10 flex items-end justify-between"><div><div className="text-6xl font-light tracking-[-.08em]">{balance}</div><div className="mt-1 text-xs text-white/45">care points held</div></div><div className="grid h-14 w-14 place-items-center rounded-full bg-[var(--accent)] text-[var(--dark)]"><Zap size={22} /></div></div><div className="mt-8 h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full w-3/4 rounded-full bg-[var(--accent)]" /></div><div className="mt-3 flex justify-between text-[10px] text-white/45"><span>steady momentum</span><span>75%</span></div></div></div><div className="flex items-end justify-between text-xs text-white/45"><span className="max-w-[190px] leading-5">Veil is a softer interface for on-chain possibility.</span><span className="flex items-center gap-1"><LockKeyhole size={13} /> private by default</span></div></div>
        </div>
      </section>

      <div className="overflow-hidden border-y border-[var(--line)] bg-[var(--dark)] py-3 text-[10px] font-semibold uppercase tracking-[.25em] text-white/55"><div className="mx-auto flex max-w-7xl justify-between gap-12 px-5 lg:px-10"><span>Veil / care as infrastructure</span><span className="hidden sm:inline">✦</span><span className="hidden sm:inline">your pace / your proof / your keys</span><span>Web3 for softer futures</span></div></div>

      <section id="story" className="mx-auto max-w-7xl scroll-mt-24 px-5 py-24 lg:px-10 lg:py-36"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-xs font-semibold uppercase tracking-[.22em] text-[var(--accent)]">01 / The premise</p><p className="mt-4 max-w-xs text-sm leading-6 text-[var(--muted)]">A different kind of protocol, built around the pace of being human.</p></div><div><h2 className="max-w-4xl text-4xl font-medium leading-tight tracking-[-.04em] sm:text-6xl">Veil lets you carry the proof you need without handing over the story behind it. <em className="font-serif font-normal text-[var(--accent)]">And it can be yours.</em></h2><p className="mt-8 max-w-2xl text-lg leading-8 text-[var(--muted)]">Veil lets you carry the proof you need without handing over the story behind it. More agency. Less exposure. A softer layer by design. The technology stays in the background, doing the careful work so the human moment can stay in the foreground.</p></div></div></section>

      <section id="protocol" className="scroll-mt-24 bg-[var(--soft)]"><div className="mx-auto max-w-7xl px-5 py-24 lg:px-10 lg:py-32"><div className="mb-14 flex flex-wrap items-end justify-between gap-6"><div><p className="text-xs font-semibold uppercase tracking-[.22em] text-[var(--accent)]">02 / The protocol</p><h2 className="mt-4 text-4xl font-medium tracking-[-.04em] sm:text-5xl">A few ways to<br /><em className="font-serif font-normal">feel held.</em></h2></div><span className="flex items-center gap-2 text-sm text-[var(--muted)]"><span className="h-2 w-2 rounded-full bg-[var(--accent)]" /> designed for return visits</span></div><div className="grid gap-4 md:grid-cols-3"><article className="rounded-3xl bg-[var(--canvas)] p-7"><span className="text-xs font-semibold text-[var(--accent)]">01</span><Wallet className="my-12 text-[var(--accent)]" size={25} /><h3 className="text-xl font-medium">Name your intention</h3><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Start with what you want to feel, make, or protect. The first signal is always yours.</p></article><article className="rounded-3xl bg-[var(--dark)] p-7 text-white"><span className="text-xs font-semibold text-[var(--accent)]">02</span><Sparkles className="my-12 text-[var(--accent)]" size={25} /><h3 className="text-xl font-medium">Let the network help</h3><p className="mt-3 text-sm leading-6 text-white/55">Open coordination gives your intention somewhere to go, without asking you to become an expert.</p></article><article className="rounded-3xl bg-[var(--canvas)] p-7"><span className="text-xs font-semibold text-[var(--accent)]">03</span><Shield className="my-12 text-[var(--accent)]" size={25} /><h3 className="text-xl font-medium">Keep what matters</h3><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Your choices, proof, and pace stay yours. Nothing extra needs to be revealed.</p></article></div></div></section>

      <section id="signal" className="mx-auto max-w-7xl scroll-mt-24 px-5 py-24 lg:px-10 lg:py-36"><div className="grid gap-12 lg:grid-cols-[1fr_.8fr]"><div><p className="text-xs font-semibold uppercase tracking-[.22em] text-[var(--accent)]">03 / Your signal</p><h2 className="mt-5 max-w-xl text-4xl font-medium tracking-[-.04em] sm:text-6xl">Progress that leaves a <em className="font-serif font-normal text-[var(--accent)]">kind trace.</em></h2><p className="mt-7 max-w-lg text-lg leading-8 text-[var(--muted)]">The dashboard is a quiet place to notice what is changing. No leaderboards. No pressure. Just enough signal to return to yourself.</p><button onClick={beginRitual} className="mt-9 inline-flex items-center gap-3 rounded-full border border-[var(--line)] px-5 py-3 text-sm font-medium transition hover:border-[var(--accent)] hover:bg-[var(--soft)]" disabled={busy}>{joined ? 'Your ritual is in motion' : 'Save an intention'} <ArrowRight size={16} /></button>{notice && <p className="mt-4 flex items-center gap-2 text-sm text-[var(--accent)]"><Check size={15} />{notice}</p>}</div><div className="rounded-[2rem] border border-[var(--line)] bg-[var(--soft)] p-7"><div className="flex items-center justify-between border-b border-[var(--line)] pb-5"><span className="text-xs font-semibold uppercase tracking-[.18em]">your private ledger</span><CircleHelp size={16} className="text-[var(--muted)]" /></div><div className="py-7"><p className="text-sm text-[var(--muted)]">recorded moments</p><strong className="mt-2 block text-6xl font-medium tracking-[-.06em]">{entries.length.toString().padStart(2, '0')}</strong></div><div className="space-y-3">{entries.slice(0, 2).map((entry, index) => <div key={index} className="flex items-center justify-between rounded-2xl bg-[var(--canvas)] px-4 py-3 text-sm"><span className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-[var(--accent)]" />{entry.mood || 'intentional'}</span><span className="text-xs text-[var(--muted)]">synced</span></div>)}</div></div></div></section>
    </main>

    <footer className="border-t border-[var(--line)]"><div className="mx-auto flex max-w-7xl flex-col gap-6 px-5 py-8 text-xs text-[var(--muted)] sm:flex-row sm:items-center sm:justify-between lg:px-10"><span className="font-medium text-[var(--ink)]">zenheaven / veil</span><span>© 2026 — a softer layer for the open web</span><span className="flex items-center gap-2"><LockKeyhole size={13} /> built with consent</span></div></footer>
  </div>
}

export default App

createRoot(document.getElementById('root')).render(<App />)
